export default function RootLayout({ children, params }) {

  return (
    <html lang={params.lang} dir={params.lang}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return [{lang: 'tr', lang: 'en', lang: '(tr)'}];
}
